# Generated by Django 5.2 on 2025-12-20 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=255, verbose_name="Titre du blog"),
                ),
                ("contenu", models.TextField(verbose_name="Contenu du blog")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blogs/images/",
                        verbose_name="Image du blog",
                    ),
                ),
                (
                    "date_publication",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de publication"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="Nom et prénom")),
                (
                    "objet",
                    models.CharField(max_length=255, verbose_name="Objet du message"),
                ),
                (
                    "numero_telephone",
                    models.CharField(
                        max_length=255, verbose_name="Numéro de téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Email de l'entreprise"
                    ),
                ),
                ("contenu", models.TextField(verbose_name="Message")),
                (
                    "date_envoi",
                    models.DateTimeField(auto_now=True, verbose_name="Date d'envoi"),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.CreateModel(
            name="DemandeDevis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="Nom et prénom")),
                (
                    "numero_telephone",
                    models.CharField(
                        max_length=255, verbose_name="Numéro de téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Email de l'utilisateur"
                    ),
                ),
                ("contenu", models.TextField(verbose_name="Message")),
                (
                    "service_souhaite",
                    models.TextField(verbose_name="Services souhaités"),
                ),
                (
                    "date_envoi",
                    models.DateTimeField(auto_now=True, verbose_name="Date d'envoi"),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Service demandé",
                "verbose_name_plural": "Services demandés",
            },
        ),
        migrations.CreateModel(
            name="EntrepriseContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_entreprise",
                    models.CharField(
                        max_length=255, verbose_name="Nom de l'entreprise"
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        max_length=255, verbose_name="Adresse de l'entreprise"
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="Localisation"),
                ),
                (
                    "numero_telephone",
                    models.CharField(
                        max_length=255,
                        verbose_name="Numéro de téléphone de l'entreprise",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Email de l'entreprise"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Contact de l'entreprise",
                "verbose_name_plural": "Contacts des entreprises",
            },
        ),
        migrations.CreateModel(
            name="Equipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="Nom du membre")),
                (
                    "poste",
                    models.CharField(max_length=255, verbose_name="Poste du membre"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="equipe/photos/",
                        verbose_name="Photo du membre",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Membre de l'équipe",
                "verbose_name_plural": "Membres de l'équipe",
            },
        ),
        migrations.CreateModel(
            name="News_letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        verbose_name="Email de l'utilisateur",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Date d\\inscription de l'utilisateur ",
                    ),
                ),
            ],
            options={
                "verbose_name": "News letter",
                "verbose_name_plural": "News letter",
            },
        ),
        migrations.CreateModel(
            name="PaysDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="Nom du pays")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description du pays"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pays_destinations/images/",
                        verbose_name="Image du pays",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Pays de destination",
                "verbose_name_plural": "Pays de destination",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=255, verbose_name="Titre du service"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description du service"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/images/",
                        verbose_name="Image du service",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.CreateModel(
            name="PackService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=255, verbose_name="Titre du pack"),
                ),
                (
                    "prix",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix du pack"
                    ),
                ),
                (
                    "liste_services_inclus",
                    models.CharField(
                        max_length=255,
                        verbose_name="Liste des services inclus dans le pack",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packs",
                        to="shine.service",
                        verbose_name="Service associé au pack",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pack de service",
                "verbose_name_plural": "Packs de services",
            },
        ),
    ]
