# Generated by Django 5.2 on 2025-12-20 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(
                max_length=254,
                validators=[
                    django.core.validators.EmailValidator(message="Email invalide")
                ],
                verbose_name="Email de l'utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="demandedevis",
            name="email",
            field=models.EmailField(
                max_length=254,
                validators=[
                    django.core.validators.EmailValidator(message="Email invalide")
                ],
                verbose_name="Email de l'utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="news_letter",
            name="email",
            field=models.EmailField(
                max_length=254,
                validators=[
                    django.core.validators.EmailValidator(message="Email invalide")
                ],
            ),
        ),
    ]
