# Generated by Django 5.2 on 2025-12-20 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0002_alter_contactmessage_email_alter_demandedevis_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="numero_telephone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le numéro doit inclure l'indicatif international (ex: +226...)",
                        regex="^\\+\\d{9,15}$",
                    )
                ],
                verbose_name="Numéro de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="demandedevis",
            name="numero_telephone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le numéro doit inclure l'indicatif international (ex: +226...)",
                        regex="^\\+\\d{9,15}$",
                    )
                ],
                verbose_name="Numéro de téléphone",
            ),
        ),
    ]
