# Generated by Django 5.2 on 2025-12-22 15:22

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0003_alter_contactmessage_numero_telephone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="numero_telephone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Numéro de téléphone"
            ),
        ),
    ]
