# Generated by Django 5.2 on 2025-12-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0005_alter_demandedevis_numero_telephone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="packservice",
            old_name="pack",
            new_name="service",
        ),
        migrations.RemoveField(
            model_name="packservice",
            name="prix",
        ),
        migrations.RemoveField(
            model_name="packservice",
            name="titre",
        ),
        migrations.AddField(
            model_name="service",
            name="prix",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Prix du pack"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="packservice",
            name="liste_services_inclus",
            field=models.TextField(
                help_text="Écrivez chaque avantage sur une nouvelle ligne.",
                verbose_name="Liste des services inclus",
            ),
        ),
    ]
