# Generated by Django 5.2 on 2025-12-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0006_rename_pack_packservice_service_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="prix",
        ),
        migrations.AddField(
            model_name="packservice",
            name="prix",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Prix du pack"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="packservice",
            name="liste_services_inclus",
            field=models.CharField(
                help_text="Écrivez chaque avantage sur une nouvelle ligne.",
                verbose_name="Liste des services inclus",
            ),
        ),
    ]
