# Generated by Django 5.2 on 2025-12-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0007_remove_service_prix_packservice_prix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="packservice",
            name="titre_pack",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Titre du pack"
            ),
        ),
    ]
