# Generated by Django 5.2 on 2025-12-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0008_packservice_titre_pack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packservice",
            name="liste_services_inclus",
            field=models.TextField(
                help_text="Écrivez chaque service inclus du pack sur une nouvelle ligne.",
                verbose_name="Services inclus",
            ),
        ),
    ]
