# Generated by Django 5.2 on 2025-12-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0009_alter_packservice_liste_services_inclus"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="services/hero_images/",
                verbose_name="Image principale du service",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="text_hero",
            field=models.TextField(
                blank=True, null=True, verbose_name="Texte de l'image principale"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="titre_blanc",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Titre blanc du service",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="titre_shine",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Titre shine du service",
            ),
        ),
    ]
