# Generated by Django 5.2 on 2025-12-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0010_service_hero_image_service_text_hero_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="image",
            new_name="image_service",
        ),
        migrations.RemoveField(
            model_name="service",
            name="hero_image",
        ),
    ]
