# Generated by Django 5.2 on 2025-12-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0011_rename_image_service_image_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="button_hero_fist",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Texte du premier bouton de l'image principale",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="button_hero_second",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Texte du second bouton de l'image principale",
            ),
        ),
    ]
