# Generated by Django 5.2 on 2025-12-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0012_service_button_hero_fist_service_button_hero_second"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="bg_color",
            field=models.CharField(default="#F7F9FE", max_length=20),
        ),
        migrations.AddField(
            model_name="service",
            name="btn_class",
            field=models.CharField(default="btn-responsive-primaryl", max_length=50),
        ),
        migrations.AddField(
            model_name="service",
            name="show_decor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="text_color",
            field=models.CharField(default="#6c757d", max_length=20),
        ),
        migrations.AddField(
            model_name="service",
            name="title_color",
            field=models.CharField(default="#122046", max_length=20),
        ),
    ]
