# Generated by Django 5.2 on 2025-12-24 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0013_service_bg_color_service_btn_class_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["-date_publication"],
                "verbose_name": "Article de Blog",
                "verbose_name_plural": "Articles de Blog",
            },
        ),
        migrations.AddField(
            model_name="blog",
            name="services_associes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shine.service",
                verbose_name="Services associés",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="date_publication",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de publication"
            ),
        ),
    ]
