# Generated by Django 5.2 on 2025-12-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0014_alter_blog_options_blog_services_associes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvisClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_client",
                    models.CharField(max_length=255, verbose_name="Nom du client"),
                ),
                (
                    "poste_client",
                    models.CharField(max_length=255, verbose_name="Poste du client"),
                ),
                (
                    "photo_client",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avis_clients/photos/",
                        verbose_name="Photo du client",
                    ),
                ),
                ("avis", models.TextField(verbose_name="Avis du client")),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="Est validé / publié"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Avis client",
                "verbose_name_plural": "Avis clients",
            },
        ),
    ]
