# Generated by Django 5.2 on 2025-12-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0015_avisclient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avisclient",
            options={
                "ordering": ["-id"],
                "verbose_name": "Avis client",
                "verbose_name_plural": "Avis clients",
            },
        ),
    ]
