# Generated by Django 5.2 on 2025-12-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0016_alter_avisclient_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="Membre actif / visible"
            ),
        ),
        migrations.AlterField(
            model_name="equipe",
            name="poste",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Poste du membre"
            ),
        ),
    ]
