# Generated by Django 5.2 on 2025-12-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0017_equipe_is_active_alter_equipe_poste"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipe",
            options={
                "ordering": ["nom"],
                "verbose_name": "Membre de l'équipe",
                "verbose_name_plural": "Membres de l'équipe",
            },
        ),
        migrations.AddField(
            model_name="paysdestination",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="Visible sur le site"
            ),
        ),
    ]
