# Generated by Django 5.2 on 2025-12-29 09:22

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0018_alter_equipe_options_paysdestination_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatutBourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(max_length=50, verbose_name="Nom du statut"),
                ),
                (
                    "couleur_classe",
                    models.CharField(
                        default="success",
                        help_text="Classe Bootstrap (success, warning, danger, primary)",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Statut des bourses",
                "verbose_name_plural": "Statuts des bourses",
            },
        ),
        migrations.AlterModelOptions(
            name="paysdestination",
            options={
                "ordering": ["nom"],
                "verbose_name": "Pays de destination",
                "verbose_name_plural": "Pays de destination",
            },
        ),
        migrations.CreateModel(
            name="Bourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=255, verbose_name="Titre de la bourse"),
                ),
                (
                    "pays",
                    models.ImageField(
                        upload_to="bourses/pays/", verbose_name="Image du pays associé"
                    ),
                ),
                (
                    "universite",
                    models.CharField(max_length=255, verbose_name="Université"),
                ),
                (
                    "montant_info",
                    models.CharField(
                        max_length=255,
                        verbose_name="Information montant (ex: 1 900€/mois)",
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        max_length=50,
                        verbose_name="Type de badge (ex: Excellence, Résidence)",
                    ),
                ),
                (
                    "description_detaillee",
                    ckeditor.fields.RichTextField(
                        verbose_name="Détails complets de la bourse"
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("date_publication", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Publié")),
                (
                    "statut",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bourses",
                        to="shine.statutbourse",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_publication"],
            },
        ),
    ]
