# Generated by Django 5.2 on 2025-12-31 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0019_statutbourse_alter_paysdestination_options_bourse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demandedevis",
            name="slug",
        ),
    ]
