# Generated by Django 5.2 on 2026-01-04 22:42

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0021_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_complet", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("pays", django_countries.fields.CountryField(max_length=2)),
                (
                    "numero_telephone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shine.paysdestination",
                    ),
                ),
            ],
        ),
    ]
