# Generated by Django 5.2 on 2026-01-08 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0022_consultation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SouscriptionSoutien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "niveau_etude",
                    models.CharField(max_length=50, verbose_name="niveau etude"),
                ),
                (
                    "objectif_principal",
                    models.CharField(max_length=100, verbose_name="objectif_principal"),
                ),
                ("matieres", models.TextField(blank=True, verbose_name="matiere")),
                ("statut", models.CharField(default="EN_ATTENTE", max_length=20)),
                (
                    "date_demande",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date envoi de la souscription"
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shine.packservice",
                        verbose_name="pack_souscrit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
