# Generated by Django 5.2 on 2026-01-08 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0023_souscriptionsoutien"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SouscriptionEtablissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_etablissement",
                    models.CharField(max_length=255, verbose_name="nom etablissement"),
                ),
                ("nombre_eleves", models.CharField(max_length=50)),
                (
                    "problemes_identifies",
                    models.TextField(verbose_name="probleme identifie"),
                ),
                ("statut", models.CharField(default="EN_ATTENTE", max_length=20)),
                (
                    "date_demande",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date envoie de la souscription"
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shine.packservice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SouscriptionEtude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dernier_diplome", models.CharField(max_length=150)),
                ("pays_destination", models.CharField(max_length=100)),
                ("filiere_visee", models.CharField(max_length=150)),
                ("statut", models.CharField(default="EN_ATTENTE", max_length=20)),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shine.packservice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SouscriptionMobilite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_visa", models.CharField(max_length=150)),
                ("pays_destination", models.CharField(max_length=100)),
                ("date_prevue", models.DateField()),
                ("statut", models.CharField(default="EN_ATTENTE", max_length=20)),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shine.packservice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
