# Generated by Django 5.2 on 2026-01-08 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shine", "0024_souscriptionetablissement_souscriptionetude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SouscriptionLogement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ville_destination",
                    models.CharField(
                        max_length=100, verbose_name="Ville de destination"
                    ),
                ),
                (
                    "date_arrivee_prevue",
                    models.CharField(
                        max_length=100, verbose_name="Date d'arrivée (ou période)"
                    ),
                ),
                (
                    "type_logement_recherche",
                    models.CharField(max_length=200, verbose_name="Type de logement"),
                ),
                (
                    "budget_loyer_max",
                    models.CharField(
                        max_length=100, verbose_name="Budget loyer mensuel"
                    ),
                ),
                (
                    "details_vol",
                    models.TextField(
                        blank=True, verbose_name="Détails du vol ou besoins spécifiques"
                    ),
                ),
                ("statut", models.CharField(default="EN_ATTENTE", max_length=20)),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shine.packservice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Souscription Logement",
            },
        ),
    ]
