# Generated by Django 5.2 on 2025-12-29 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usercompte", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="birth_year",
        ),
    ]
