# Generated by Django 5.2 on 2025-12-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usercompte", "0002_remove_user_birth_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_year",
            field=models.DateField(
                blank=True, null=True, verbose_name="Année de naissance"
            ),
        ),
    ]
