# Generated by Django 5.2 on 2025-12-29 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usercompte", "0003_user_birth_year"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
