# Generated by Django 5.2 on 2025-12-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usercompte", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="code_postal",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Code Postal"
            ),
        ),
    ]
