# Generated by Django 5.2 on 2025-12-29 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usercompte", "0005_user_code_postal"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfilUtilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profil_name",
                    models.CharField(
                        max_length=100, verbose_name="Nom du profil utilisateur"
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Utilisateur",
                "verbose_name_plural": "Profils Utilisateurs",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="profil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="utilisateurs",
                to="usercompte.profilutilisateur",
                verbose_name="Profil utilisateur",
            ),
        ),
    ]
