# Generated by Django 5.2 on 2025-12-31 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usercompte", "0006_profilutilisateur_user_profil"),
    ]

    operations = [
        migrations.CreateModel(
            name="EtapeDossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(max_length=100, verbose_name="Nom de l'étape"),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordre d'affichage (1, 2, 3...)"
                    ),
                ),
                (
                    "description_aide",
                    models.TextField(
                        blank=True, verbose_name="Message d'aide pour l'étudiant"
                    ),
                ),
                (
                    "couleur_badge",
                    models.CharField(
                        choices=[
                            ("primary", "Bleu (En cours)"),
                            ("warning", "Orange (En attente)"),
                            ("success", "Vert (Terminé)"),
                            ("danger", "Rouge (Bloqué)"),
                            ("secondary", "Gris (À venir)"),
                        ],
                        default="secondary",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration : Étape de dossier",
                "ordering": ["ordre"],
            },
        ),
        migrations.CreateModel(
            name="SuiviDossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_specifique",
                    models.TextField(
                        blank=True,
                        verbose_name="Commentaire personnalisé pour cet étudiant",
                    ),
                ),
                ("derniere_maj", models.DateTimeField(auto_now=True)),
                (
                    "etape_actuelle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="usercompte.etapedossier",
                        verbose_name="Étape actuelle",
                    ),
                ),
                (
                    "etudiant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suivi_dossier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
